### ISSUE TITLE
move icons

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#149]
![Image](https://github.com/novaday-co/nova_kudos_flutter/assets/9497923/e73f9b42-97e4-4602-b911-cef185b9d2ad)

توی مانیتور فاصله بین عنوان و آیکون زیاد است و عملا آیکون ها کارایی خود را از دست داده. لطفا آیکون ها به سمت راست (پشت عنوان) منتقل بشن با یک فاصله مناسب 10-15 پیکسلی از عنوان

**Comment by AmirJabbari** [comment]
Done
