### ISSUE TITLE
fix header size

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#150]
https://github.com/novaday-co/nova_kudos_flutter/assets/9497923/ed45b3c6-346c-45ae-9dbf-dbcc99bbe7b3

اندازه هدر باید در تب های مختلف ثابت باشد در تب های دوم سوم کمی بالا پایین میشود - آواتار کاربر بهتر است تغییر سایز ندهد

**Comment by AmirJabbari** [comment]
Done
