### ISSUE TITLE
use same coin icon

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#155]
![Image](https://github.com/novaday-co/nova_kudos_flutter/assets/9497923/d58bd0d3-5ddd-47e8-8200-b0056616ba2e)

برای سکه از یک آیکون استفاده شود تا در ذهن بماند. در اینجا انگار تفاوتی بین ارزش این دو سکه وجود دارد

**Comment by AmirJabbari** [comment]
Done
