### ISSUE TITLE
OTP Login

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#19]
<div dir="rtl">

- کاربر شماره همراهشو وارد میکنه اگر توی سیستم عضو باشه لاگین میشه توی آخرین شرکتی که داخلش بوده اگر نه خطا میده که "کاربر در سیستم کودوس پیدا نشد"
- بعد از لاگین، اطلاعات کاربر در آن شرکت ( company_user ) شامل اسم، موبایل، عکس، عنوان شغلی، موجودی سکه و ریالی، تعداد نوتیفیکیشن های خوانده نشده، ریسورس شرکت هایی که داخلش عضو هست ( همراه با فیلد is_default و  role در آن شرکت و نرخ سکه در آن شرکت ) و role سیستمی ( is_superadmin ) براش برمیگرده. 
- این اطلاعاتی که بعد از لاگین برمیگرده توی یک ریکوئست دیگه هم باید در دسترس باشه ( مثلا account یا profile ) که برنامه نویس در مواقع لزوم بتونه از سرور بگیره 
- مقدار token فقط در ریکوئست (لاگین) به کاربر برمیگرده و در ریکوئست های دیگه در دسترس نیست.
- بعد از لاگین یک فیلد تحت عنوان login_count برمیگرده که مربوط به تعداد لاگین کاربر هست. وقتی که کاربر برای اولین بار داره لاگین میکنه 1 برمیگرده. دفعه بعدی 2 و … .
- یک ریکوئست برای ارسال مجدد کد لازم داریم. این ریکوئست باید فقط وقتی کار کنه که کاربر بیشتر از 60 ثانیه از ایجاد کد قبلیش گذشته باشه. برای لاگین هم اگر کد با موفقیت ارسال شده بود نباید ریکوئست لاگین زیر 60 ثانیه کد sms کنه، فقط true برمیگردونه و کاربر رو به صفحه otp هدایت میکنه
- بعد از لاگین، کاربر وارد صفحه داشبورد میشه 

- تا اینجا انتظار میره داشبورد فقط بخش بالایی رو درست نشون بده ( موجودی ها و اطلاعات کاربر ) و همچنین منوی بغل کار کنه تا بتونیم بقیه بخش ها رو یواش یواش پیاده کنیم … .

</div>

**Comment by itsysnb** [comment]
@mohsen-jalali 
@faridfr 
This part is done.
