### ISSUE TITLE
Coin Rate - Admin

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#22]
<div dir="rtl">

- یکی از منو های "مدیر شرکت" است
- یک ریکوئست GET لازم است برای این صفحه که دو مقدار را برمیگرداند. مقدار نرخ فعلی و ارزش کل سیستم بر اساس آن نرخ ( مقدار کل سکه های کاربران آن شرکت*نرخ سکه قبلی + موجودی های ریالی کاربران آن شرکت ) - طبیعتا این ریکوئست باید فقط برای مدیر شرکت کار کند.
- یک ریکوئست PUT لازم است برای آپدیت نرخ سکه آن شرکت. فقط همین نرخ را تغییر میدهد و به هیچ چیز دیگری دست نمی زند.
- یک ریکوئست get دیگر لازم است برای اینکه وقتی عدد را تغییر میدهند ارزش سیستم را برمبنای عدد جدید ( که به عنوان ورودی به ریکوئست میدهند ) به کلاینت اعلام کنیم

</div>

**Comment by itsysnb** [comment]
@mohsen-jalali 
@faridfr 
This part is done.

**Comment by AmirJabbari** [comment]
Done
