### ISSUE TITLE
Buy from the market

### ISSUE THREAD

**Issue by faridfr** [novaday-co/nova_kudos_flutter#39]
<div dir="rtl">

- یک ریکوئست POST لازم است که بتوانیم با ارسال آی دی یکی از محصولات داخل بازارچه ( که در تسک های قبلی پیاده سازی شده است ) آن را خریداری کنیم
- بعد از خرید موفقیت آمیز باید یک کد سفارش به کاربر برگردانده شود . جهت پیگیری

</div>

**Comment by AmirJabbari** [comment]
Done
